### ISSUE TITLE
Same for pages

### ISSUE THREAD

**Issue by Andrasx** [calliaweb/featured-custom-post-type-widget-for-genesis#18]
Hi,
I love this widget. Can I make it work for pages as well? Or is it only for posts?

**Comment by calliaweb** [comment]
The quick answer is no. Pages aren't grouped by category, tag or taxonomy like posts and other custom post types. Robin's Featured Content Widget plugin https://robincornett.com/downloads/sixtenpress-featured-content/ works with pages and may be worth looking at.
